services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "file:./dev.db"
      AUTH_SECRET: "yoursecretkey"
